env:
  es2021: true
  node: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - prettier
rules:
  camelcase: error
  spaced-comment: error
  quotes:
    - error
    - single
  no-duplicate-imports: error
